---
apiVersion: v1
kind: Namespace
metadata:
  name: virtualfit

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: virtualfit-inference-gpu-scaler
  namespace: virtualfit
spec:
  scaleTargetRef:
    name: inference-service
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 15
  cooldownPeriod: 300
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 50
            periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Percent
            value: 100
            periodSeconds: 30
          - type: Pods
            value: 2
            periodSeconds: 30
          selectPolicy: Max
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus.monitoring.svc.cluster.local:9090
      metricName: gpu_utilization
      threshold: "70"
      query: |
        avg(DCGM_FI_DEV_GPU_UTIL{namespace="virtualfit"})
  - type: prometheus
    metadata:
      serverAddress: http://prometheus.monitoring.svc.cluster.local:9090
      metricName: gpu_memory_utilization
      threshold: "80"
      query: |
        avg(DCGM_FI_DEV_FB_USED{namespace="virtualfit"} / DCGM_FI_DEV_FB_FREE{namespace="virtualfit"} * 100)
  - type: prometheus
    metadata:
      serverAddress: http://prometheus.monitoring.svc.cluster.local:9090
      metricName: request_queue_length
      threshold: "10"
      query: |
        sum(virtualfit_queue_length{namespace="virtualfit"})
  - type: prometheus
    metadata:
      serverAddress: http://prometheus.monitoring.svc.cluster.local:9090
      metricName: active_requests
      threshold: "5"
      query: |
        sum(virtualfit_active_requests{namespace="virtualfit"})
  - type: prometheus
    metadata:
      serverAddress: http://prometheus.monitoring.svc.cluster.local:9090
      metricName: request_latency_p95
      threshold: "5000"
      query: |
        histogram_quantile(0.95, rate(virtualfit_request_duration_seconds_bucket{namespace="virtualfit"}[2m])) * 1000

---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-prometheus
  namespace: virtualfit
spec:
  secretTargetRef: []

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: inference-service-pdb
  namespace: virtualfit
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: inference-service
