name: Digicloset Checks & Tests
on: [push, pull_request]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r monitoring/requirements.txt
      - name: Run DB migration check
        run: python db/migration_check.py
      - name: Run integration tests
        run: pytest -q
